[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
accord_registry = "9W1Zh89ykeWSbXVTgHHgeUcyUTGSs2XAbMRvY1uR1gU"

[programs.devnet]
accord_registry = "9W1Zh89ykeWSbXVTgHHgeUcyUTGSs2XAbMRvY1uR1gU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/rammsey/.config/solana/accord-registry.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
